"use client"

import Link from "next/link"
import { useState } from "react"
import { ArrowRight, Boxes, Check, Globe2, Menu, Receipt, ShieldCheck, ShoppingCart, Users, X } from "lucide-react"
import { Button } from "@/components/ui/button"
import { brandConfig } from "@/lib/brand-config"

const capabilities = [
  { icon: ShoppingCart, title: "Fast point of sale", description: "Build a cart, attach a customer, take payment, and create an invoice from one focused workspace." },
  { icon: Boxes, title: "Inventory that stays actionable", description: "Track stock health, adjust quantities, manage suppliers, and surface replenishment work early." },
  { icon: Receipt, title: "Orders through fulfillment", description: "Keep manual, POS, and storefront orders together with payment and courier status." },
  { icon: Users, title: "Owner and staff workflows", description: "Give staff access to the modules they need while the owner keeps the complete operating view." },
  { icon: Globe2, title: "A hosted bilingual storefront", description: "Shape English and Bangla content, publish products, and receive delivery-only cash-on-delivery orders." },
  { icon: ShieldCheck, title: "One tenant boundary", description: "Organization-scoped data and permissions keep each business workspace isolated." },
]

export default function InventoryPOSLanding() {
  const [menuOpen, setMenuOpen] = useState(false)
  return <div className="min-h-screen overflow-x-hidden bg-background text-foreground">
    <header className="sticky top-0 z-50 border-b bg-background/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6"><Link href="/" className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-primary font-extrabold text-primary-foreground">B</span><span className="font-extrabold tracking-tight">{brandConfig.name}</span></Link><nav className="hidden items-center gap-7 text-sm font-medium md:flex"><a href="#product" className="text-muted-foreground hover:text-foreground">Product</a><a href="#storefront" className="text-muted-foreground hover:text-foreground">Storefront</a><a href="#workflow" className="text-muted-foreground hover:text-foreground">How it works</a></nav><div className="hidden items-center gap-2 md:flex"><Button variant="ghost" asChild><Link href="/auth/login">Log in</Link></Button><Button asChild><Link href="/auth/register">Create your workspace<ArrowRight className="ml-2 size-4" /></Link></Button></div><Button variant="ghost" size="icon" className="md:hidden" onClick={() => setMenuOpen(value => !value)} aria-label={menuOpen ? "Close menu" : "Open menu"}>{menuOpen ? <X className="size-5" /> : <Menu className="size-5" />}</Button></div>{menuOpen && <nav className="border-t p-4 md:hidden"><div className="mx-auto flex max-w-7xl flex-col gap-2"><a href="#product" className="rounded-lg p-3" onClick={() => setMenuOpen(false)}>Product</a><a href="#storefront" className="rounded-lg p-3" onClick={() => setMenuOpen(false)}>Storefront</a><Button variant="outline" asChild><Link href="/auth/login">Log in</Link></Button><Button asChild><Link href="/auth/register">Create your workspace</Link></Button></div></nav>}</header>

    <main>
      <section className="relative"><div className="absolute inset-x-0 top-0 -z-10 h-[42rem] bg-[radial-gradient(circle_at_20%_20%,hsl(var(--primary)/0.16),transparent_38%),radial-gradient(circle_at_80%_25%,hsl(var(--accent-foreground)/0.13),transparent_35%)]" /><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 py-20 sm:px-6 sm:py-28 lg:grid-cols-[1.05fr_0.95fr] lg:py-36"><div><p className="inline-flex rounded-full border bg-card px-3 py-1 text-xs font-semibold uppercase tracking-[0.14em] text-primary">Commerce operations for growing shops</p><h1 className="mt-6 max-w-4xl text-4xl font-black leading-[1.05] tracking-[-0.04em] sm:text-6xl lg:text-7xl">Run the counter.<br /><span className="text-primary">Publish the store.</span><br />Know what needs attention.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">BusOS brings POS, inventory, orders, customers, expenses, staff access, and a hosted bilingual storefront into one operating system for your business.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button size="lg" asChild><Link href="/auth/register">Create your workspace<ArrowRight className="ml-2 size-4" /></Link></Button><Button size="lg" variant="outline" asChild><a href="#product">Explore the product</a></Button></div><p className="mt-4 text-xs text-muted-foreground">Subscription terms and trial availability are shown during registration.</p></div>
      <div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-5 -z-10 rotate-2 rounded-[2rem] bg-accent" /><div className="overflow-hidden rounded-2xl border bg-card shadow-xl"><div className="flex items-center justify-between border-b p-4"><div><p className="text-sm font-bold">Today</p><p className="text-xs text-muted-foreground">Operating overview</p></div><span className="rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-semibold text-emerald-700 dark:text-emerald-300">Store open</span></div><div className="grid gap-3 p-4 sm:grid-cols-2"><div className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">Sales</p><p className="mt-2 text-2xl font-extrabold tabular-nums">৳24,680</p><p className="mt-1 text-xs text-muted-foreground">38 orders</p></div><div className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">Needs attention</p><p className="mt-2 text-2xl font-extrabold tabular-nums">7</p><p className="mt-1 text-xs text-amber-700 dark:text-amber-400">Low-stock products</p></div><div className="col-span-full rounded-xl border p-4"><div className="flex items-center justify-between"><p className="text-sm font-bold">Recent orders</p><span className="text-xs text-primary">View all</span></div>{["Storefront · #1048", "POS · #1047", "Manual · #1046"].map((item, index) => <div key={item} className="mt-3 flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-muted text-xs font-bold">{index + 1}</span><span className="min-w-0 flex-1 truncate text-sm">{item}</span><span className="text-sm font-semibold">৳{[1850, 640, 3290][index].toLocaleString()}</span></div>)}</div></div></div></div></div></section>

      <section id="product" className="border-y bg-card py-20 sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">A connected workspace</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">The daily tools, designed to work together.</h2><p className="mt-4 text-muted-foreground">Business data stays connected from product setup to sale, fulfillment, reporting, and the public catalog.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{capabilities.map(item => <article key={item.title} className="rounded-2xl border bg-background p-6 transition-colors hover:border-primary/40"><span className="grid size-11 place-items-center rounded-xl bg-primary/10 text-primary"><item.icon className="size-5" /></span><h3 className="mt-5 text-lg font-bold">{item.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{item.description}</p></article>)}</div></div></section>

      <section id="storefront" className="py-20 sm:py-28"><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-2"><div className="rounded-[2rem] bg-[#151923] p-6 text-white shadow-xl sm:p-10"><div className="rounded-2xl bg-white p-6 text-[#151923]"><div className="flex items-center justify-between"><p className="font-black">Your shop</p><span className="text-xs">EN · বাংলা</span></div><div className="mt-8 rounded-2xl bg-[#fbf8f2] p-8 text-center"><p className="text-xs font-bold uppercase tracking-widest text-[#e85f4c]">New collection</p><p className="mt-2 text-3xl font-black">Products your customers can order</p><p className="mt-3 text-sm text-[#686b73]">Published from the same catalog you use at the counter.</p></div><div className="mt-4 grid grid-cols-3 gap-3">{[1,2,3].map(item => <div key={item}><div className="aspect-square rounded-xl bg-[#f0ece4]" /><div className="mt-2 h-2 rounded bg-[#ddd5ca]" /></div>)}</div></div></div><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Hosted storefront</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Turn the same catalog into a customer-facing store.</h2><p className="mt-5 text-muted-foreground">Choose a subdomain, adjust your colors, write English and Bangla sections, preview responsive layouts, and publish when the draft is ready.</p><ul className="mt-6 space-y-3">{["English and Bangla content with English fallback", "Guest, delivery-only, cash-on-delivery checkout", "Storefront orders enter the same fulfillment queue", "Product availability follows inventory"].map(item => <li key={item} className="flex gap-3 text-sm"><Check className="mt-0.5 size-4 shrink-0 text-emerald-600" />{item}</li>)}</ul></div></div></section>

      <section id="workflow" className="border-y bg-accent/40 py-20"><div className="mx-auto max-w-5xl px-4 text-center sm:px-6"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-accent-foreground">Start with your real workflow</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">Set up the business once. Operate from one place.</h2><div className="mt-10 grid gap-4 text-left sm:grid-cols-3">{[["01","Create your organization","Add business details and invite the staff who will use BusOS."],["02","Add products and stock","Build the catalog that powers inventory, POS, and your storefront."],["03","Sell and fulfill","Record counter sales, publish online, and manage every order through delivery."]].map(([step,title,body]) => <div key={step} className="rounded-2xl border bg-card p-6"><span className="text-xs font-black text-primary">{step}</span><h3 className="mt-3 font-bold">{title}</h3><p className="mt-2 text-sm text-muted-foreground">{body}</p></div>)}</div><Button size="lg" className="mt-10" asChild><Link href="/auth/register">Create your workspace<ArrowRight className="ml-2 size-4" /></Link></Button></div></section>
    </main>
    <footer className="border-t"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between sm:px-6"><p>Copyright {new Date().getFullYear()} {brandConfig.name}. Commerce, clearly run.</p><div className="flex gap-5"><Link href="/auth/login">Log in</Link><Link href="/auth/register">Register</Link></div></div></footer>
  </div>
}
